package com.movie.demo.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

// Recommended Lombok annotations for clean code
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

@Entity
@Getter
@Setter
@NoArgsConstructor // JPA requires a no-argument constructor
@AllArgsConstructor // Optional, but useful for quick object creation
public class Movies {

    // Primary Key (ID)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-increment for MySQL
    private Long id;

    // Fields that correspond to your form and database columns
    private String title;
    private String genre;
    private Integer releaseYear;
    private String director;
    private Double rating; // Example field

    // --- Note: Getters and Setters are automatically generated by Lombok's @Getter/@Setter ---
    // --- Note: Constructors are automatically generated by Lombok's @NoArgsConstructor/@AllArgsConstructor ---
}